name: "Test action"

on:
  push:
    branches: [ "master" ]

env:
  NOMAD_VERSION: "1.9.1" # or: "latest"
  NOMAD_ADDRS: "http://147.45.159.235:4646/"
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  INFRO_REPO: book-hub-umsp/bh-infrastructure

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: '${{ env.INFRO_REPO }}'
        ref: 'master'
        token: '${{ secrets.WORKFLOW_TOKEN }}'
    - name: Setup `nomad`
      uses: hashicorp/setup-nomad@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}
    - run: nomad job plan -help
    - name: Nomad test
      env:
        NOMAD_ADDRS: ${{ env.NOMAD_ADDRS }}
      run: |
        nomad job plan -token "${{ secrets.NOMAD_JOB_TOKEN }}" -var ROOT_PASS "root" -var main-api-version "root" nomad/jobs/bh-back.hcl
